### PR TITLE
Config and db

### PR DESCRIPTION
**Pull request by qhool**
This PR addresses the configuration mechanism in chloroform and streamlines starting up the test server.  README.md is updated to indicate the 'normal' mode for setting up configuration.  For production, the CHLOROFORM_SETTINGS env var can be set to point to the config file.

It also fixes the relationship between madlibs and questions (it is many-to-many now, and each relationship includes a 'key' (this is the value in the question template "${keyname}")).

### CODE REVIEW

**Comment by meteor-man** [comment]
re "improved method for starting the server", are we keeping runserver.py?

**Review by Tmana — APPROVED** [review]

**Comment by qhool** [comment]
Good point about runserver.py -- I don't think it was adding anything, so I've removed it.

**Comment by meteor-man** [comment]
Hah! that was the main file to run the application and load the configs.
http://flask.pocoo.org/docs/0.11/patterns/packages/

**Comment by qhool** [comment]
`chloroform/__main__.py` now serves the same purpose; it's why `python -m chloroform` works to start the server.

**Review by carias8 — APPROVED** [review]

**Review by johncookds — APPROVED** [review]

**Pull request merged**
