### PR TITLE
FE: 'add client' feature

### PR DESCRIPTION
**Pull request by ppope**
Implemented buttons for adding a new client and for saving.

### CODE REVIEW

**Comment by meteor-man** [comment]
Have you tested your 'post' method? What are you sending to the backend?
What are the items that you're returning? You may not need that if it's from my method...
I guess we need to show a message when the new client gets created successfully.

**Comment by carias8** [comment]
Yeah it seems like the post is hitting POST /clients/my_new_client. You want to POST to /clients?name=my_new_client

You should receive a `success` message (if it succeeds of course) and use this to provide feedback to user

**Comment by ppope** [comment]
Awesome. Thanks for clarifying that.

**Comment by ppope** [comment]
@carias8 @meteor-man hmm so I get the following when I try to hit that endpoint. Can you advise?
```
127.0.0.1 - - [29/Nov/2016 09:57:36] "POST /clients?name=test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1617, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1603, in raise_routing_exception
    raise FormDataRoutingRedirect(request)
FormDataRoutingRedirect: A request was sent to this URL (http://127.0.0.1:5000/clients?name=test) but a redirect was issued automatical
ly by the routing system to "http://127.0.0.1:5000/clients/?name=test".  The URL was defined with a trailing slash so Flask will automa
tically redirect to the URL with the trailing slash if it was accessed without one.  Make sure to directly send your POST-request to th
is URL since we can't make browsers or HTTP clients redirect with form data reliably or without user interaction.

```

**Comment by carias8** [comment]
Sorry seems like you need a trailing slash. That's why it's trying to redirect

So you want: "POST /clients/?name=test" instead of "POST /clients?name=test"

* also: use the params parameter of the http.post method to include name instead of hardcoding into url

**Review by johncookds — APPROVED** [review]

**Comment by ppope** [comment]
(Don't merge this yet). Okay, I fixed the path, but I get this now:
```
127.0.0.1 - - [29/Nov/2016 10:54:15] "POST /clients/?name=test HTTP/1.1" 405 -
```

405 -> (METHOD NOT ALLOWED)

**Comment by ppope** [comment]
We tried adding the hanging "/" to the route and adding the client name to the `params` dict, but still getting some weirdness with the request. E.g.

```
127.0.0.1 - - [29/Nov/2016 11:55:41] "POST /clients/?name=&name=test HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/phil/anaconda/envs/py2/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/phil/phillip.pope/NCF-DS/2016-fall/end-to-end/chloroform/chloroform/routes.py", line 52, in create
    instance = model(**request.form.to_dict())
TypeError: __init__() takes exactly 2 arguments (1 given)
```

**Comment by ppope** [comment]
@meteor-man I was able to add a new client to the database. What we had was right, it was just that the database was still in a rollback state from a previous error. It does the auto-increment thing automatically.

@carias8  We had to hack a few things to get it to work. Please review.
*  "/clients/" is the right endpoint
* For `create` in routes.py,
    * `request.data` works instead of `request.form`.
    * Request data was initially received as a string. We made it into a dict with json.loads.

**Review by carias8 — APPROVED** [review]

**Comment by meteor-man** [comment]
@carias8 What happens if the MIME type is not specified in the request? Also what's the difference between request.json and request.get_json() and which one should be preferred?

**Comment by carias8** [comment]
@meteor-man it's the client that specifies the MIME type so the real question is what did you pass to Angular's `$http.post()`? By default Angular uses `application/json`

Difference between the two:
`request.json` will be populated with a python dict version of the data when MIME is json
`request.get_json()` tells the request to parse the data as json and allows you to set a `force=True` flag so it doesn't complain about MIME types

source:[http://stackoverflow.com/questions/20001229/how-to-get-posted-json-in-flask](http://stackoverflow.com/questions/20001229/how-to-get-posted-json-in-flask)

which should we use? Whichever. I can see arguments for why we should always expect the MIME type to be json and arguments for why we should be explicit

**Review by meteor-man — APPROVED** [review]

**Comment by ppope** [comment]
Merged master into this branch.

**Pull request merged**
